baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'OHBM Aperture'

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  # media:
  #   output: false
  #   permalink: /media/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: "images"
    values:
      image: true

sass:
  style: expanded # possible values: nested expanded compact compressed

google_analytics_id: null
